apiVersion: v1
kind: Service
metadata:
  name: sf-petclinic-service
  labels:
    app: sf-petclinic
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: sf-petclinic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sf-petclinic
  name: sf-petclinic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sf-petclinic
    spec:
      containers:
      - image: stdcluster.icp:8500/default/spring-framework-petclinic
        name: sf-petclinic
        ports:
        - containerPort: 8080
          protocol: TCP
